---
site_name: stock-sent-earnings
site_description: Documentation for the stock-sent-earnings Python Project
site_author: Mark Quinn
repo_url: https://github.com/finsite/stock-sent-earnings
theme:
  name: material
nav:
  - Home: index.md
  - API Reference: api.md
  - More Details: more-details.md
  - Other Topic: other-topic.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
markdown_extensions:
  - admonition
  - toc:
      permalink: true
