---
apiVersion: v1
kind: Service
metadata:
  name: stock-sent-earnings
spec:
  type: ClusterIP
  selector:
    app: stock-sent-earnings
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
